


USE [master]
GO

/****** Object:  Database [CareerSetting]    Script Date: 12.03.2020 21:19:46 ******/
CREATE DATABASE [CareerSetting]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CareerSetting', FILENAME = N'C:\Users\B.Albayrak\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\CareerSetting.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CareerSetting_log', FILENAME = N'C:\Users\B.Albayrak\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\CareerSetting.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CareerSetting].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CareerSetting] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [CareerSetting] SET ANSI_NULLS ON 
GO

ALTER DATABASE [CareerSetting] SET ANSI_PADDING ON 
GO

ALTER DATABASE [CareerSetting] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [CareerSetting] SET ARITHABORT ON 
GO

ALTER DATABASE [CareerSetting] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CareerSetting] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CareerSetting] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CareerSetting] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CareerSetting] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [CareerSetting] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [CareerSetting] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CareerSetting] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [CareerSetting] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CareerSetting] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CareerSetting] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CareerSetting] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CareerSetting] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CareerSetting] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CareerSetting] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CareerSetting] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CareerSetting] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CareerSetting] SET RECOVERY FULL 
GO

ALTER DATABASE [CareerSetting] SET  MULTI_USER 
GO

ALTER DATABASE [CareerSetting] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CareerSetting] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CareerSetting] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CareerSetting] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CareerSetting] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CareerSetting] SET QUERY_STORE = OFF
GO

USE [CareerSetting]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [CareerSetting] SET  READ_WRITE 
GO

